default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000
  password:
  host: localhost
  port: 5432


development:
  <<: *default
  database: sitelab_development
  username: erikdungan


test:
  <<: *default
  database: sitelab_test
  username: erikdungan


production:
  <<: *default
  database: sitelab_production
