default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000
  username: erikdungan
  password:
  host: localhost
  port: 5432


development:
  <<: *default
  database: sitelab_development

test:
  <<: *default
  database: sitelab_test

production:
  <<: *default
  database: sitelab_production
