# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45e7d995a78db45641417504fb1d9731927adec50803bf2264b4eaf4e53024691ff414f7edb50dd09ef16f43bfa1efd29f474bea9fe26f1bc6c470dcda719e3

test:
  secret_key_base: 7c209e417373985cb240b9491107c9e647a4c668f9a1b2abe2c4743c2ebd952f701c05dbfa287f41f67860461b92d39094d400d52a2a80c5a57871c452d12aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
